
* Wikimedia Open Science Fellowship 17/18

*Contact* I keep this notes openly in the hope to get feedback on my project. Please consider creating issues for this repository, but you can also contact me [[http://felix11h.github.io/][directly]]. I would love to hear from you. Thank you for your interest and input!

** Project description
I want to create and publish a fully open computational research study. Read a more detailed description of the project [[https://de.wikiversity.org/wiki/Wikiversity:Fellow-Programm_Freies_Wissen/Einreichungen/Open_computational_research_study][here]]. 

** Updates 

**** exploring Singularity
I had a deeper look at [[http://singularity.lbl.gov/index.html][Singularity]] and built some containers from my Docker images. I've run into several problems that I haven't really been able to fix. For the current project, Singularity does not seem a good fit.

**** research on archiving of Docker images
Docker images can be archived with the command ~docker save felix11/my-image > my-image.tar~ and images can be restored from an archive with ~docker load < my-image.tar~. Uploading the ~.tar~ archives allows for unique identification via a DOI. This [[https://www.software.ac.uk/blog/2016-09-12-reproducible-research-citing-your-execution-environment-using-docker-and-doi][article]] goes into some more detail.

**** Docker image for Sumatra 0.5.2
the research I plan to publish was recorded in a Sumatra 0.5.2 lab notebook. I built a Docker image ([[https://hub.docker.com/r/felix11h/docker-sumatra-0.5.2/][Docker Hub]], [[https://github.com/Felix11H/docker-sumatra-0.5.2][GitHub repository]]) that contains Sumatra 0.5.2. With this my results are accessible. I posted on the Sumatra-user mailing list to share the process of creating the image.

**** talk at Google Munich
I'm giving a short presentation on Sumatra and my plans for the fellowship at the Google Summer of Code Munich Meetup on 14.11.2017. The slides for my talk can be found [[https://github.com/Felix11H/GSoC14_munich_slides][here]].


** Notes & Resources

Here I'm collecting all sorts of resources relevant to my project. Some of those links were pointed out to me by [[https://github.com/jibe-b][@jibe-b]]. Many thanks for this!

**** articles on Docker & reproducibility
- Grüning et al. (2017) /Practical computational reproducibility in the life sciences/  [[https://www.biorxiv.org/content/early/2017/10/11/200683.full.pdf%2Bhtml][biorxiv.org]] 
  : Makes the point of reproducibility on multiple scales.
  : go from Conda -> Docker -> full virtual machine
- Haines at el. (2016) /Reproducible Research: Citing your execution environment using Docker and a DOI/ [[https://www.software.ac.uk/blog/2016-09-12-reproducible-research-citing-your-execution-environment-using-docker-and-doi][software.ac.uk]]
  : use "docker save felix11/my-image > my-image.tar" and 
  : and upload to Zenodo

**** research articles that include a Docker environment
- Bremges et al. (2015) /Deeply sequenced metagenome and metatranscriptome of a biogas-producing microbial community from an agricultural production-scale biogas plant/ [[https://gigascience.biomedcentral.com/articles/10.1186/s13742-015-0073-6][gigascience.biomedcentral.com]] Code: [[https://github.com/metagenomics/2015-biogas-cebitec][github.com]]
  : Dockerfile and GitHub repository included. Link to Docker Hub
  : seems already deprecated. Did not archive Docker image or 
  : GitHub repository. Good: Comment on the resources necessary to : complete all computations
- Clarkson et al. (2015) /The archaeology, chronology and stratigraphy of Madjedbebe (Malakunanja II): A site in northern Australia with early occupation/ [[https://www.sciencedirect.com/science/article/pii/S0047248415000846?via%253Dihub][sciencedirect.com]] Code: [[http://dx.doi.org/10.6084/m9.figshare.1297059][10.6084/m9.figshare.1297059]]
  : Only published Dockerfile, compiled image not part of figshare 
  : archive

**** events
- ICLR 2018 Reproducibility Challenge [[http://www.cs.mcgill.ca/~jpineau/ICLR2018-ReproducibilityChallenge.html][cs.mcgill.ca]]
- Reproducibility Clearinghouse [[https://meta-lab.co/rc/][meta-lab.co/rc]] 

** Tasks

**** [November] collect resources and information for technical implementation of computational research study
- examples of studies who have used Docker/Singularity to publish their computational results?
- studies who have published using Sumatra or other electronic lab notebooks?

**** [November] write a short tech report outlining the challenges and proposed implementations in the study

Draft [[file:tech_report.org][tech_report.org]]

- collect and process feedback

**** [December] Can I build the Docker container using Conda installations? 
this a point made by Grüning et al. (2017). See also [[file:tech_report.org][tech_report.org]]. Current Docker container: [[https://hub.docker.com/r/felix11h/aniso_netw_env/][hub.docker.com]]
