
* Wikimedia Open Science Fellowship 17/18

*Contact* I keep this notes openly in the hope to get feedback on my project. Please consider creating issues for this repository, but you can also contact me [[http://felix11h.github.io/][directly]]. I would love to hear from you. Thank you for your interest and input!

** Project description
I want to create and publish a fully open computational research study. Read a more detailed description of the project [[https://de.wikiversity.org/wiki/Wikiversity:Fellow-Programm_Freies_Wissen/Einreichungen/Open_computational_research_study][here]]. 

** Updates 

# **** a proof-of-concept for my publication
# I've started developing a proof-of-concept 

**** eLife Innovation Sprint 10-11.05.2018
I'll be participating in the [[https://elifesciences.org/events/c40798c3/elife-innovation-sprint-2018?utm_source%3Devent&utm_medium%3Dwebpage&utm_campaign%3DInnovSprint][eLife Innovation Sprint]] in Cambridge in May. I will report more on the project/prototype I'll be working on here.

**** talk at Bordeaux Neurocampus 25.04.2018
I'll give a talk at the [[http://www.bordeaux-neurocampus.fr/en/index.html][Bordeaux Neurocampus]] on reproducibility on computational research and my fellowship project. This event is part of the retreat of my [[http://brain.mpg.de/graduate-studies.html][PhD program]] to Bordeaux. The talk should be open to the public and I will post information about it here. Slides will be posted here as well (Slides are available [[https://github.com/Felix11H/bordeaux18-slides][here]]).

**** Docker image for project [Pt. 2]
I've published the final(?) version of the image I will use for this study. It's hosted on [[https://hub.docker.com/r/felix11h/aniso_netw_env/][Docker Hub]].

**** #brainTC Twitter talk
My #brainTC Twitter is available [[https://twitter.com/RealBrainTC/status/971819097053941760][here]]. The updated blog post is [[http://felix11h.github.io/blog/open-comp-rsc-concept][here]]. To create the animations, I used [[https://github.com/phw/peek][peek]] to record GIFs from my screen and annotated using ImageMagick with code as I published [[https://gist.github.com/Felix11H/4fffc3338a70b900bc3a8d9964d44f2e][here]].

**** Twitter talk and blog post improvements
I'll be working on this in coming weeks. Please look out for an updated version of the blog and a draft of the #brainTC talk.

**** Abstract for Brain Twitter Conference #brainTC
[[https://github.com/VTeckentrup][@VTeckentrup]] suggested to submit to present our projects at [[https://brain.tc/][#brainTC]], the Brain Twitter Conference. I submitted the following abstract

*Title*: Making computational neuroscience research reproducible - A Docker based approach

*Abstract*: Results in computational neuroscience research are often the product of complex numerical simulations. The ability to successfully reproduce these results  -- a core requirement that all of research should satisfy -- not only depends on the availability of the research code: In many cases the computational environment consists of a highly specialized toolset that may be difficult or even impossible to replicate. Here I show how Docker, an operating-system-level virtualization tool, can be employed to package the computational environment of a study to make it accessible to others. To demonstrate this concept, I developed a prototype that includes (1) example computations, (2) generated data, (3) documentation in form of an electronic lab notebook and (4) the full computational environment. Published in this form, reproduction of the computational results becomes easily possible, independent of the platform and without the need to meet any dependencies other than Docker. This approach offers a promising perspective for computational neuroscience research as an increased accessibility of the results and the computations that generate them will benefit the transparency and, ultimately, the quality of the research output.

*Keywords*: reproducibility, open science, docker

The conference will take place on March 8, 2018. If my talk gets accepted I will update here on my assigned time slot. 

**** Proof of concept for an Open Computational Research Study
In a [[http://felix11h.github.io/blog/open-comp-rsc-concept][blog post]] I'm describing how I plan to publish my computational research to ensure it's accessible and reproducible. For this I have created an [[https://doi.org/10.5281/zenodo.1145677][example study]] that demonstrates how the fully published study can be interacted with in concept.

**** Docker image for the project
I've written, compiled and tested the Docker image for my computational project. Based on Ubuntu 16.04 the image includes Python with the standard scientific libraries, TeX Live, Sumatra and Graph tool. The image is found on [[https://hub.docker.com/r/felix11h/docker-aniso-netw-dev/][Docker Hub]].

**** reproducing Docker images
I was interested how well the building of Docker images works some time after they have been written. In this [[https://github.com/Felix11H/docker-reproduction-of-published-images][repository]] and this connected [[https://hub.docker.com/r/felix11h/docker-reproduction-of-published-images/][Docker Hub entry]], I tested the Docker images from the research publications I'm aware of that publish a Dockerfile. The results are:
#+BEGIN_QUOTE
 build successful: 2
 build failed: 1
#+END_QUOTE

Personally, I think it's not a question of "if" but "when" a Dockerfile won't build anymore due to missing dependencies. It's good to share the Dockerfile and encourage people to compile on their own (trust), but Docker images most also be archived!

**** exploring Singularity
I had a deeper look at [[http://singularity.lbl.gov/index.html][Singularity]] and built some containers from my Docker images. I've run into several problems that I haven't really been able to fix. For the current project, Singularity does not seem a good fit.

**** research on archiving of Docker images
Docker images can be archived with the command ~docker save felix11h/my-image > my-image.tar~ and images can be restored from an archive with ~docker load < my-image.tar~. Uploading the ~.tar~ archives allows for unique identification via a DOI. This [[https://www.software.ac.uk/blog/2016-09-12-reproducible-research-citing-your-execution-environment-using-docker-and-doi][article]] goes into some more detail.

**** Docker image for Sumatra 0.5.2
the research I plan to publish was recorded in a Sumatra 0.5.2 lab notebook. I built a Docker image ([[https://hub.docker.com/r/felix11h/docker-sumatra-0.5.2/][Docker Hub]], [[https://github.com/Felix11H/docker-sumatra-0.5.2][GitHub repository]]) that contains Sumatra 0.5.2. With this my results are accessible. I posted on the Sumatra-user mailing list to share the process of creating the image.

**** talk at Google Munich
I'm giving a short presentation on Sumatra and my plans for the fellowship at the Google Summer of Code Munich Meetup on 14.11.2017. The slides for my talk can be found [[https://github.com/Felix11H/GSoC14_munich_slides][here]].


** Notes & Resources

Here I'm collecting all sorts of resources relevant to my project. Some of those links were pointed out to me by [[https://github.com/jibe-b][@jibe-b]]. Many thanks for this!

**** articles on Docker & reproducibility
- C. Titus Brown (2017) /How I learned to stop worrying and love the coming archivability crisis in scientific software/ [[http://ivory.idyll.org/blog/2017-pof-software-archivability.html][ivory.idyll.org]]
  : Docker not necessarily suitable longterm archiving of 
  : scientific software. Should acknowledge that software 
  : has a half life and focus on "inspectability" after 
  : maintaining repeatability can no longer be justified.
- Bruno Vieira (2017) /A truly reproducible scientific paper?/
  : Use pip freeze or npm shrinkwrap, nix package manager.
  : Similar point to Grüning's first tier of reproducbility
- Grüning et al. (2017) /Practical computational reproducibility in the life sciences/  [[https://www.biorxiv.org/content/early/2017/10/11/200683.full.pdf%2Bhtml][biorxiv.org]] 
  : Makes the point of reproducibility on multiple scales.
  : go from Conda -> Docker -> full virtual machine
- Haines at el. (2016) /Reproducible Research: Citing your execution environment using Docker and a DOI/ [[https://www.software.ac.uk/blog/2016-09-12-reproducible-research-citing-your-execution-environment-using-docker-and-doi][software.ac.uk]]
  : use "docker save felix11h/my-image > my-image.tar" and 
  : and upload to Zenodo
- Ghosh et al. (2017) /A very simple, re-executable neuroimaging publication/ doi: [[http://dx.doi.org/10.12688/f1000research.10783.2][10.12688/f1000research.10783.2]]
  : proposed structure: 1) data file, 2) workflow file, 
  : 3) execution environment specification, 4) results
  : ---
  : >> Great result: When Docker is used, they observed NO
  : >> difference in results when anaylsis is run on different 
  : >> platform (Linux vs. Mac environment)


**** research articles that include a Docker environment
- Bremges et al. (2015) /Deeply sequenced metagenome and metatranscriptome of a biogas-producing microbial community from an agricultural production-scale biogas plant/ [[https://gigascience.biomedcentral.com/articles/10.1186/s13742-015-0073-6][gigascience.biomedcentral.com]] Code: [[https://github.com/metagenomics/2015-biogas-cebitec][github.com]]
  : Dockerfile and GitHub repository included. Link to Docker Hub
  : seems already deprecated. Did not archive Docker image or 
  : GitHub repository. Good: Comment on the resources necessary to
  : complete all computations
- Clarkson et al. (2015) /The archaeology, chronology and stratigraphy of Madjedbebe (Malakunanja II): A site in northern Australia with early occupation/ [[https://www.sciencedirect.com/science/article/pii/S0047248415000846?via%253Dihub][sciencedirect.com]] Code: [[http://dx.doi.org/10.6084/m9.figshare.1297059][10.6084/m9.figshare.1297059]]
  : Only published Dockerfile, compiled image not part of figshare 
  : archive


**** resources on Singularity
- Pablo Escobar "Working with Singularity" slides [[https://pescobar.github.io/singularity-slides/#1][pescobar.github.io]]

**** events
- ICLR 2018 Reproducibility Challenge [[http://www.cs.mcgill.ca/~jpineau/ICLR2018-ReproducibilityChallenge.html][cs.mcgill.ca]]
- Reproducibility Clearinghouse [[https://meta-lab.co/rc/][meta-lab.co/rc]] 

** Tasks

**** [January] complete the midterm report
Template at [[https://de.wikiversity.org/wiki/Wikiversity:Fellow-Programm_Freies_Wissen/Zwischenbericht][de.wikiversity.org]]

**** [November] collect resources and information for technical implementation of computational research study
- examples of studies who have used Docker/Singularity to publish their computational results?
- studies who have published using Sumatra or other electronic lab notebooks?

**** [November] write a short tech report outlining the challenges and proposed implementations in the study
Draft [[file:tech_report.org][tech_report.org]]

- collect and process feedback

**** [December] Can I build the Docker container using Conda installations? 
this a point made by Grüning et al. (2017). See also [[file:tech_report.org][tech_report.org]]. Current Docker container: [[https://hub.docker.com/r/felix11h/aniso_netw_env/][hub.docker.com]]
