* Wikimedia Open Science Fellowship 17/18

*Contact* You can create issues for this repository, but you can also contact me [[http://felix11h.github.io/][directly]]. I would be very grateful for any type of input!

** Resources 
The description for my project is found [[https://de.wikiversity.org/wiki/Wikiversity:Fellow-Programm_Freies_Wissen/Einreichungen/Open_computational_research_study][here]]. 

** Notes
The following interesting links were shared with me by [[https://github.com/jibe-b][@jibe-b]]
 - Grüning et al. (2017) /Practical computational reproducibility in the life sciences/  [[https://www.biorxiv.org/content/early/2017/10/11/200683.full.pdf%2Bhtml][biorxiv.org]]
 - ICLR 2018 Reproducibility Challenge [[http://www.cs.mcgill.ca/~jpineau/ICLR2018-ReproducibilityChallenge.html][cs.mcgill.ca]]
 - Reproducibility Clearinghouse [[https://meta-lab.co/rc/][meta-lab.co/rc]]

** TODOs

*** collect resources and information for technical implementation of computational research study
- examples of studies who have used Docker/Singularity to publish their computational results?
- studies who have published using Sumatra or other electronic lab notebooks?

*** [November] write a short tech report outlining the challenges and proposed implementations in the study

Draft [[file:tech_report.org][tech_report.org]]

- collect and process feedback
 

** Updates 
